# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_remove_users_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('contributer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrib', to='travel.Users')),
                ('join', models.ManyToManyField(related_name='joins', to='travel.Users')),
            ],
        ),
    ]
